name: lalsuite-dev
channels:
  - conda-forge
dependencies:
  - autoconf
  - automake
  - bc
  - cfitsio
  - doxygen
  - fftw
  - freezegun
  - c-compiler
  - gsl
  - h5py
  - hdf5
  - healpy
  - ldas-tools-framecpp
  - libframe
  - ligo-segments
  - lscsoft-glue
  - make
  - metaio
  - numpy
  - pkg-config
  - pytest
  - python
  - scipy
  - six
  - swig >=3.0.10
  - texlive-core
  - zlib
